version: "2.1"
services:
  wireguard:
    image: deluge-wireguard
    container_name: deluge-wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # - SERVERURL=wireguard.domain.com #optional
      # - SERVERPORT=51820 #optional
      # - PEERS=1 #optional
      # - PEERDNS=auto #optional
      # - INTERNAL_SUBNET=10.13.13.0 #optional
      # - ALLOWEDIPS=0.0.0.0/0 #optional
      # - PERSISTENTKEEPALIVE_PEERS= #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - /mnt/blackbox/media:/mnt/blackbox/media
      # - /lib/modules:/lib/modules #optional
    ports:
      - 51820:51820/udp
      - 8112:8112
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
